name: Gracious Studios
favicon: null
layout_spectrum: 0.97717
typography_spectrum: 0.66583
title: Gracious Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#72b443'
    - '#f4feeb'
    - '#98b878'
    - '#a5d37d'
    - '#c8eda7'
  brandStrength: 0.5625
  lightness: 0.36716778902336955
  saturation: 0.2122746491804719
  rhythmicContrast: 0.7513136053457856
purpose: []
