name: Gracious Studios
favicon: null
layout_spectrum: 0.07543621817603707
typography_spectrum: 0.29588985396549106
title: Gracious Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.607902584830299
  lightness: 0.36716778902336955
  saturation: 0.2122746491804719
  rhythmicContrast: 0.7513136053457856
purpose: []
